// Station name → NLC (National Location Code) lookup (TfL-21). Pure module.
//
// The Apply form identifies stations by numeric NLC (StartNlcId/FinishNlcId),
// but we only hold station NAMES from the journey CSV. This resolves one to the
// other. STATION_NLC is generated from TfL NUMBAT open data (build-nlc-map.mjs)
// and keyed by a normalised name so "Ruislip", "ruislip", and "Ruislip [London
// Underground]" all resolve.
//
// Multi-mode interchanges (Canary Wharf appears as LU=852, DLR=842, EL=6560)
// collapse to one normalised key with several candidate NLCs. The Apply form's
// station picker is filtered by the Mode you select first, so we disambiguate
// by the claim's ModeId: pick the candidate whose modes include it. If we can't
// tell (ambiguous, or the name isn't in the map) we return null and the caller
// leaves the field for the user — we never guess an NLC, because a wrong code
// would file a claim for the wrong station.

/** One NLC candidate for a normalised station name, with the transport modes
 * (Apply-form ModeId values) it serves — used to disambiguate interchanges. */
export interface NlcCandidate {
  nlc: number;
  modes: number[];
}

/** Normalise a station name to the STATION_NLC key form: lowercase; drop a
 * "[…]" source suffix and "(…)" disambiguator; "&"→"and"; apostrophes removed;
 * mode words / abbreviations (underground, dlr, lu, lo, nr, el, tfl…) stripped;
 * punctuation collapsed to single spaces. Applied to both map keys and queries
 * so "Canary Wharf LU" and a CSV's "Canary Wharf" land on the same key. */
export function normStation(name: string): string {
  return String(name ?? '')
    .toLowerCase()
    .replace(/\[[^\]]*\]/g, ' ')                 // "[london underground]"
    .replace(/\([^)]*\)/g, ' ')                  // "(Bak)" "(DIS)" "(H&C)" "(Olympia)"
    .replace(/&/g, ' and ')
    .replace(/['’]/g, '')                        // "king's" → "kings", not "king s"
    .replace(/\b(underground|overground|elizabeth line|dlr|rail|station|ug|lu|lo|nr|el|tfl)\b/g, ' ')
    .replace(/[^a-z0-9 ]+/g, ' ')                // punctuation → space
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Resolve a station name (optionally constrained to a ModeId) against a map.
 * Pure, so tests inject a fixture. Exact normalised match first, then an
 * unambiguous prefix match. Among several NLC candidates, disambiguate by
 * modeId; if that leaves 0 or >1, return null rather than guess.
 */
export function resolveNlc(
  name: string,
  modeId: number | null,
  map: Record<string, NlcCandidate[]>,
): number | null {
  const key = normStation(name);
  if (!key) return null;

  let cands = Object.prototype.hasOwnProperty.call(map, key) ? map[key] : null;
  if (!cands) {
    // Tolerate a missing trailing word ("kings cross" vs "kings cross st
    // pancras"), but only when exactly one base key qualifies.
    const hits = Object.keys(map).filter(k => k.indexOf(key) === 0 || key.indexOf(k) === 0);
    if (hits.length === 1) cands = map[hits[0]];
  }
  if (!cands || cands.length === 0) return null;
  if (cands.length === 1) return cands[0].nlc;

  // Several NLCs share this name (interchange). Pick the one matching the mode.
  if (modeId != null) {
    const byMode = cands.filter(c => c.modes.indexOf(modeId) !== -1);
    if (byMode.length === 1) return byMode[0].nlc;
    // All candidates that agree on a single NLC are effectively unambiguous.
    if (byMode.length > 1) {
      const nlc = byMode[0].nlc;
      if (byMode.every(c => c.nlc === nlc)) return nlc;
    }
  }
  return null; // ambiguous → leave for the user
}

// GENERATED — populated from TfL NUMBAT open data by build-nlc-map.mjs. Keys
// are normStation() output; values are NLC candidates with their ModeIds. Do
// not hand-edit; regenerate to update.
export const STATION_NLC: Record<string, NlcCandidate[]> = {
  "abbey road": [{ nlc: 750, modes: [5] }],
  "abbey wood": [{ nlc: 5131, modes: [101] }],
  "acton central": [{ nlc: 1404, modes: [20] }],
  "acton main line": [{ nlc: 3000, modes: [101] }],
  "acton town": [{ nlc: 500, modes: [0] }],
  "aldgate": [{ nlc: 502, modes: [0] }],
  "aldgate east": [{ nlc: 503, modes: [0] }],
  "all saints": [{ nlc: 850, modes: [5] }],
  "alperton": [{ nlc: 505, modes: [0] }],
  "amersham": [{ nlc: 506, modes: [0] }],
  "anerley": [{ nlc: 5397, modes: [20] }],
  "angel": [{ nlc: 507, modes: [0] }],
  "archway": [{ nlc: 508, modes: [0] }],
  "arnos grove": [{ nlc: 509, modes: [0] }],
  "arsenal": [{ nlc: 510, modes: [0] }],
  "baker street": [{ nlc: 511, modes: [0] }],
  "balham": [{ nlc: 512, modes: [0] }],
  "bank and monument": [{ nlc: 513, modes: [0, 5] }],
  "barbican": [{ nlc: 501, modes: [0] }],
  "barking": [{ nlc: 514, modes: [0, 20] }],
  "barking riverside": [{ nlc: 1335, modes: [20] }],
  "barkingside": [{ nlc: 515, modes: [0] }],
  "barons court": [{ nlc: 516, modes: [0] }],
  "battersea park": [{ nlc: 5420, modes: [20] }],
  "battersea power": [{ nlc: 832, modes: [0] }],
  "bayswater": [{ nlc: 517, modes: [0] }],
  "beckton": [{ nlc: 895, modes: [5] }],
  "beckton park": [{ nlc: 891, modes: [5] }],
  "becontree": [{ nlc: 518, modes: [0] }],
  "belsize park": [{ nlc: 519, modes: [0] }],
  "bermondsey": [{ nlc: 787, modes: [0] }],
  "bethnal green": [{ nlc: 6961, modes: [20] }, { nlc: 520, modes: [0] }],
  "blackfriars": [{ nlc: 521, modes: [0] }],
  "blackhorse road": [{ nlc: 522, modes: [0, 20] }],
  "blackwall": [{ nlc: 882, modes: [5] }],
  "bond street": [{ nlc: 524, modes: [0, 101] }],
  "borough": [{ nlc: 525, modes: [0] }],
  "boston manor": [{ nlc: 526, modes: [0] }],
  "bounds green": [{ nlc: 527, modes: [0] }],
  "bow church": [{ nlc: 851, modes: [5] }],
  "bow road": [{ nlc: 528, modes: [0] }],
  "brent cross": [{ nlc: 529, modes: [0] }],
  "brentwood": [{ nlc: 6872, modes: [101] }],
  "brixton": [{ nlc: 778, modes: [0] }],
  "brockley": [{ nlc: 5404, modes: [20] }],
  "bromley by bow": [{ nlc: 530, modes: [0] }],
  "brondesbury": [{ nlc: 1437, modes: [20] }],
  "brondesbury park": [{ nlc: 1438, modes: [20] }],
  "bruce grove": [{ nlc: 6958, modes: [20] }],
  "buckhurst hill": [{ nlc: 531, modes: [0] }],
  "burnham": [{ nlc: 3176, modes: [101] }],
  "burnt oak": [{ nlc: 532, modes: [0] }],
  "bush hill park": [{ nlc: 6913, modes: [20] }],
  "bushey": [{ nlc: 1395, modes: [20] }],
  "caledonian road": [{ nlc: 534, modes: [0] }],
  "caledonian road and barnsbury": [{ nlc: 1439, modes: [20] }],
  "cambridge heath": [{ nlc: 6962, modes: [20] }],
  "camden road": [{ nlc: 1440, modes: [20] }],
  "camden town": [{ nlc: 535, modes: [0] }],
  "canada water": [{ nlc: 788, modes: [0, 20] }],
  "canary wharf": [{ nlc: 842, modes: [5] }, { nlc: 6560, modes: [101] }, { nlc: 852, modes: [0] }],
  "canning town": [{ nlc: 884, modes: [0, 5] }],
  "cannon street": [{ nlc: 536, modes: [0] }],
  "canonbury": [{ nlc: 1441, modes: [20] }],
  "canons park": [{ nlc: 537, modes: [0] }],
  "carpenders park": [{ nlc: 1442, modes: [20] }],
  "chadwell heath": [{ nlc: 6874, modes: [101] }],
  "chalfont and latimer": [{ nlc: 539, modes: [0] }],
  "chalk farm": [{ nlc: 540, modes: [0] }],
  "chancery lane": [{ nlc: 541, modes: [0] }],
  "charing cross": [{ nlc: 718, modes: [0] }],
  "chesham": [{ nlc: 543, modes: [0] }],
  "cheshunt": [{ nlc: 6814, modes: [20] }],
  "chigwell": [{ nlc: 544, modes: [0] }],
  "chingford": [{ nlc: 6914, modes: [20] }],
  "chiswick park": [{ nlc: 545, modes: [0] }],
  "chorleywood": [{ nlc: 546, modes: [0] }],
  "clapham common": [{ nlc: 547, modes: [0] }],
  "clapham high street": [{ nlc: 5301, modes: [20] }],
  "clapham junction": [{ nlc: 5595, modes: [20] }],
  "clapham north": [{ nlc: 548, modes: [0] }],
  "clapham south": [{ nlc: 549, modes: [0] }],
  "clapton": [{ nlc: 6926, modes: [20] }],
  "cockfosters": [{ nlc: 550, modes: [0] }],
  "colindale": [{ nlc: 551, modes: [0] }],
  "colliers wood": [{ nlc: 552, modes: [0] }],
  "covent garden": [{ nlc: 553, modes: [0] }],
  "crossharbour": [{ nlc: 854, modes: [5] }],
  "crouch hill": [{ nlc: 7406, modes: [20] }],
  "croxley": [{ nlc: 554, modes: [0] }],
  "crystal palace": [{ nlc: 5356, modes: [20] }],
  "custom house": [{ nlc: 887, modes: [5] }, { nlc: 6561, modes: [101] }],
  "cutty sark": [{ nlc: 879, modes: [5] }],
  "cyprus": [{ nlc: 893, modes: [5] }],
  "dagenham east": [{ nlc: 555, modes: [0] }],
  "dagenham heathway": [{ nlc: 556, modes: [0] }],
  "dalston junction": [{ nlc: 1443, modes: [20] }],
  "dalston kingsland": [{ nlc: 1429, modes: [20] }],
  "debden": [{ nlc: 557, modes: [0] }],
  "denmark hill": [{ nlc: 5421, modes: [20] }],
  "deptford bridge": [{ nlc: 897, modes: [5] }],
  "devons road": [{ nlc: 867, modes: [5] }],
  "dollis hill": [{ nlc: 558, modes: [0] }],
  "ealing broadway": [{ nlc: 560, modes: [0, 101] }],
  "ealing common": [{ nlc: 561, modes: [0] }],
  "earls court": [{ nlc: 562, modes: [0] }],
  "east acton": [{ nlc: 563, modes: [0] }],
  "east finchley": [{ nlc: 565, modes: [0] }],
  "east ham": [{ nlc: 566, modes: [0] }],
  "east india": [{ nlc: 883, modes: [5] }],
  "east putney": [{ nlc: 567, modes: [0] }],
  "eastcote": [{ nlc: 564, modes: [0] }],
  "edgware": [{ nlc: 568, modes: [0] }],
  "edgware road": [{ nlc: 774, modes: [0] }, { nlc: 569, modes: [0] }],
  "edmonton green": [{ nlc: 6941, modes: [20] }],
  "elephant and castle": [{ nlc: 570, modes: [0] }],
  "elm park": [{ nlc: 571, modes: [0] }],
  "elverson road": [{ nlc: 898, modes: [5] }],
  "embankment": [{ nlc: 542, modes: [0] }],
  "emerson park": [{ nlc: 7473, modes: [20] }],
  "enfield town": [{ nlc: 6959, modes: [20] }],
  "epping": [{ nlc: 572, modes: [0] }],
  "euston": [{ nlc: 574, modes: [0] }, { nlc: 1444, modes: [20] }],
  "euston square": [{ nlc: 575, modes: [0] }],
  "fairlop": [{ nlc: 576, modes: [0] }],
  "farringdon": [{ nlc: 577, modes: [0, 101] }],
  "finchley central": [{ nlc: 578, modes: [0] }],
  "finchley road": [{ nlc: 579, modes: [0] }],
  "finchley road and frognal": [{ nlc: 1445, modes: [20] }],
  "finsbury park": [{ nlc: 580, modes: [0] }],
  "forest gate": [{ nlc: 6876, modes: [101] }],
  "forest hill": [{ nlc: 5362, modes: [20] }],
  "fulham broadway": [{ nlc: 581, modes: [0] }],
  "gallions reach": [{ nlc: 894, modes: [5] }],
  "gants hill": [{ nlc: 582, modes: [0] }],
  "gidea park": [{ nlc: 6877, modes: [101] }],
  "gloucester road": [{ nlc: 583, modes: [0] }],
  "golders green": [{ nlc: 584, modes: [0] }],
  "goldhawk road": [{ nlc: 585, modes: [0] }],
  "goodge street": [{ nlc: 586, modes: [0] }],
  "goodmayes": [{ nlc: 6878, modes: [101] }],
  "gospel oak": [{ nlc: 1409, modes: [20] }],
  "grange hill": [{ nlc: 587, modes: [0] }],
  "great portland street": [{ nlc: 588, modes: [0] }],
  "green park": [{ nlc: 590, modes: [0] }],
  "greenford": [{ nlc: 589, modes: [0] }],
  "greenwich": [{ nlc: 928, modes: [5] }],
  "gunnersbury": [{ nlc: 591, modes: [0, 20] }],
  "hackney central": [{ nlc: 6977, modes: [20] }],
  "hackney downs": [{ nlc: 6867, modes: [20] }],
  "hackney wick": [{ nlc: 6978, modes: [20] }],
  "haggerston": [{ nlc: 1022, modes: [20] }],
  "hainault": [{ nlc: 592, modes: [0] }],
  "hammersmith": [{ nlc: 593, modes: [0] }, { nlc: 773, modes: [0] }],
  "hampstead": [{ nlc: 594, modes: [0] }],
  "hampstead heath": [{ nlc: 1413, modes: [20] }],
  "hanger lane": [{ nlc: 595, modes: [0] }],
  "hanwell": [{ nlc: 3191, modes: [101] }],
  "harlesden": [{ nlc: 596, modes: [0, 20] }],
  "harold wood": [{ nlc: 6879, modes: [101] }],
  "harringay green lanes": [{ nlc: 7401, modes: [20] }],
  "harrow and wealdstone": [{ nlc: 597, modes: [0, 20] }],
  "harrow on the hill": [{ nlc: 598, modes: [0] }],
  "hatch end": [{ nlc: 1398, modes: [20] }],
  "hatton cross": [{ nlc: 779, modes: [0] }],
  "hayes and harlington": [{ nlc: 3186, modes: [101] }],
  "headstone lane": [{ nlc: 1434, modes: [20] }],
  "heathrow terminal 4": [{ nlc: 7091, modes: [101] }, { nlc: 781, modes: [0] }],
  "heathrow terminal 5": [{ nlc: 9846, modes: [101] }, { nlc: 783, modes: [0] }],
  "heathrow terminals 123": [{ nlc: 780, modes: [0] }],
  "heathrow terminals 2 and 3": [{ nlc: 7090, modes: [101] }],
  "hendon central": [{ nlc: 601, modes: [0] }],
  "heron quays": [{ nlc: 855, modes: [5] }],
  "high barnet": [{ nlc: 602, modes: [0] }],
  "high street kensington": [{ nlc: 605, modes: [0] }],
  "highams park": [{ nlc: 6919, modes: [20] }],
  "highbury and islington": [{ nlc: 603, modes: [0, 20] }],
  "highgate": [{ nlc: 604, modes: [0] }],
  "hillingdon": [{ nlc: 606, modes: [0] }],
  "holborn": [{ nlc: 607, modes: [0] }],
  "holland park": [{ nlc: 608, modes: [0] }],
  "holloway road": [{ nlc: 609, modes: [0] }],
  "homerton": [{ nlc: 6979, modes: [20] }],
  "honor oak park": [{ nlc: 5418, modes: [20] }],
  "hornchurch": [{ nlc: 610, modes: [0] }],
  "hounslow central": [{ nlc: 611, modes: [0] }],
  "hounslow east": [{ nlc: 612, modes: [0] }],
  "hounslow west": [{ nlc: 613, modes: [0] }],
  "hoxton": [{ nlc: 1023, modes: [20] }],
  "hyde park corner": [{ nlc: 614, modes: [0] }],
  "ickenham": [{ nlc: 615, modes: [0] }],
  "ilford": [{ nlc: 6881, modes: [101] }],
  "imperial wharf": [{ nlc: 9586, modes: [20] }],
  "island gardens": [{ nlc: 856, modes: [5] }],
  "iver": [{ nlc: 3170, modes: [101] }],
  "kennington": [{ nlc: 616, modes: [0] }],
  "kensal green": [{ nlc: 617, modes: [0, 20] }],
  "kensal rise": [{ nlc: 1448, modes: [20] }],
  "kensington": [{ nlc: 618, modes: [0, 20] }],
  "kentish town": [{ nlc: 619, modes: [0] }],
  "kentish town west": [{ nlc: 1449, modes: [20] }],
  "kenton": [{ nlc: 620, modes: [0, 20] }],
  "kew gardens": [{ nlc: 621, modes: [0, 20] }],
  "kilburn": [{ nlc: 622, modes: [0] }],
  "kilburn high road": [{ nlc: 1415, modes: [20] }],
  "kilburn park": [{ nlc: 623, modes: [0] }],
  "king george v": [{ nlc: 523, modes: [5] }],
  "kings cross st pancras": [{ nlc: 625, modes: [0] }],
  "kingsbury": [{ nlc: 624, modes: [0] }],
  "knightsbridge": [{ nlc: 626, modes: [0] }],
  "ladbroke grove": [{ nlc: 627, modes: [0] }],
  "lambeth north": [{ nlc: 628, modes: [0] }],
  "lancaster gate": [{ nlc: 629, modes: [0] }],
  "langdon park": [{ nlc: 853, modes: [5] }],
  "langley": [{ nlc: 3171, modes: [101] }],
  "latimer road": [{ nlc: 630, modes: [0] }],
  "leicester square": [{ nlc: 631, modes: [0] }],
  "lewisham": [{ nlc: 940, modes: [5] }],
  "leyton": [{ nlc: 632, modes: [0] }],
  "leyton midland road": [{ nlc: 7402, modes: [20] }],
  "leytonstone": [{ nlc: 633, modes: [0] }],
  "leytonstone high road": [{ nlc: 7403, modes: [20] }],
  "limehouse": [{ nlc: 862, modes: [5] }],
  "liverpool street": [{ nlc: 634, modes: [0, 101] }, { nlc: 6965, modes: [20, 101] }],
  "london bridge": [{ nlc: 635, modes: [0] }],
  "london city airport": [{ nlc: 533, modes: [5] }],
  "london fields": [{ nlc: 6966, modes: [20] }],
  "loughton": [{ nlc: 636, modes: [0] }],
  "maida vale": [{ nlc: 637, modes: [0] }],
  "maidenhead": [{ nlc: 3147, modes: [101] }],
  "manor house": [{ nlc: 638, modes: [0] }],
  "manor park": [{ nlc: 6883, modes: [101] }],
  "mansion house": [{ nlc: 639, modes: [0] }],
  "marble arch": [{ nlc: 640, modes: [0] }],
  "maryland": [{ nlc: 6970, modes: [101] }],
  "marylebone": [{ nlc: 641, modes: [0] }],
  "mile end": [{ nlc: 642, modes: [0] }],
  "mill hill east": [{ nlc: 643, modes: [0] }],
  "moor park": [{ nlc: 646, modes: [0] }],
  "moorgate": [{ nlc: 645, modes: [0] }],
  "morden": [{ nlc: 647, modes: [0] }],
  "mornington crescent": [{ nlc: 648, modes: [0] }],
  "mudchute": [{ nlc: 857, modes: [5] }],
  "neasden": [{ nlc: 649, modes: [0] }],
  "new cross": [{ nlc: 5150, modes: [20] }],
  "new cross gate": [{ nlc: 5345, modes: [20] }],
  "newbury park": [{ nlc: 650, modes: [0] }],
  "nine elms": [{ nlc: 831, modes: [0] }],
  "north acton": [{ nlc: 653, modes: [0] }],
  "north ealing": [{ nlc: 654, modes: [0] }],
  "north greenwich": [{ nlc: 789, modes: [0] }],
  "north harrow": [{ nlc: 656, modes: [0] }],
  "north wembley": [{ nlc: 659, modes: [0, 20] }],
  "northfields": [{ nlc: 655, modes: [0] }],
  "northolt": [{ nlc: 657, modes: [0] }],
  "northwick park": [{ nlc: 660, modes: [0] }],
  "northwood": [{ nlc: 661, modes: [0] }],
  "northwood hills": [{ nlc: 662, modes: [0] }],
  "norwood jn": [{ nlc: 5376, modes: [20] }],
  "notting hill gate": [{ nlc: 663, modes: [0] }],
  "oakwood": [{ nlc: 664, modes: [0] }],
  "old street": [{ nlc: 665, modes: [0] }],
  "osterley": [{ nlc: 667, modes: [0] }],
  "oval": [{ nlc: 668, modes: [0] }],
  "oxford circus": [{ nlc: 669, modes: [0] }],
  "paddington": [{ nlc: 3087, modes: [101] }, { nlc: 670, modes: [0, 101] }],
  "park royal": [{ nlc: 671, modes: [0] }],
  "parsons green": [{ nlc: 672, modes: [0] }],
  "peckham rye": [{ nlc: 5423, modes: [20] }],
  "penge west": [{ nlc: 5378, modes: [20] }],
  "perivale": [{ nlc: 673, modes: [0] }],
  "piccadilly circus": [{ nlc: 674, modes: [0] }],
  "pimlico": [{ nlc: 776, modes: [0] }],
  "pinner": [{ nlc: 675, modes: [0] }],
  "plaistow": [{ nlc: 676, modes: [0] }],
  "pontoon dock": [{ nlc: 538, modes: [5] }],
  "poplar": [{ nlc: 858, modes: [5] }],
  "preston road": [{ nlc: 677, modes: [0] }],
  "prince regent": [{ nlc: 888, modes: [5] }],
  "pudding mill lane": [{ nlc: 859, modes: [5] }],
  "putney bridge": [{ nlc: 678, modes: [0] }],
  "queens park": [{ nlc: 680, modes: [0, 20] }],
  "queens road peckham": [{ nlc: 5424, modes: [20] }],
  "queensbury": [{ nlc: 679, modes: [0] }],
  "queensway": [{ nlc: 681, modes: [0] }],
  "ravenscourt park": [{ nlc: 682, modes: [0] }],
  "rayners lane": [{ nlc: 683, modes: [0] }],
  "reading": [{ nlc: 3149, modes: [101] }],
  "rectory road": [{ nlc: 6967, modes: [20] }],
  "redbridge": [{ nlc: 684, modes: [0] }],
  "regents park": [{ nlc: 685, modes: [0] }],
  "richmond": [{ nlc: 686, modes: [0, 20] }],
  "rickmansworth": [{ nlc: 687, modes: [0] }],
  "roding valley": [{ nlc: 688, modes: [0] }],
  "romford": [{ nlc: 6886, modes: [20, 101] }],
  "rotherhithe": [{ nlc: 1039, modes: [20] }],
  "royal albert": [{ nlc: 890, modes: [5] }],
  "royal oak": [{ nlc: 690, modes: [0] }],
  "royal victoria": [{ nlc: 886, modes: [5] }],
  "ruislip": [{ nlc: 691, modes: [0] }],
  "ruislip gardens": [{ nlc: 692, modes: [0] }],
  "ruislip manor": [{ nlc: 693, modes: [0] }],
  "russell square": [{ nlc: 694, modes: [0] }],
  "seven kings": [{ nlc: 6893, modes: [101] }],
  "seven sisters": [{ nlc: 698, modes: [0, 20] }],
  "shadwell": [{ nlc: 860, modes: [5] }, { nlc: 1082, modes: [20] }],
  "shenfield": [{ nlc: 6888, modes: [101] }],
  "shepherds bush": [{ nlc: 700, modes: [0] }, { nlc: 9587, modes: [20] }],
  "shepherds bush market": [{ nlc: 775, modes: [0] }],
  "shoreditch high street": [{ nlc: 1024, modes: [20] }],
  "silver street": [{ nlc: 6972, modes: [20] }],
  "sloane square": [{ nlc: 702, modes: [0] }],
  "slough": [{ nlc: 3172, modes: [101] }],
  "snaresbrook": [{ nlc: 703, modes: [0] }],
  "south acton": [{ nlc: 1452, modes: [20] }],
  "south ealing": [{ nlc: 704, modes: [0] }],
  "south hampstead": [{ nlc: 1451, modes: [20] }],
  "south harrow": [{ nlc: 707, modes: [0] }],
  "south kensington": [{ nlc: 708, modes: [0] }],
  "south kenton": [{ nlc: 709, modes: [0, 20] }],
  "south quay": [{ nlc: 861, modes: [5] }],
  "south ruislip": [{ nlc: 710, modes: [0] }],
  "south tottenham": [{ nlc: 7404, modes: [20] }],
  "south wimbledon": [{ nlc: 711, modes: [0] }],
  "south woodford": [{ nlc: 712, modes: [0] }],
  "southall": [{ nlc: 3187, modes: [101] }],
  "southbury": [{ nlc: 6947, modes: [20] }],
  "southfields": [{ nlc: 705, modes: [0] }],
  "southgate": [{ nlc: 706, modes: [0] }],
  "southwark": [{ nlc: 784, modes: [0] }],
  "st james street": [{ nlc: 6973, modes: [20] }],
  "st jamess park": [{ nlc: 695, modes: [0] }],
  "st johns wood": [{ nlc: 696, modes: [0] }],
  "st pauls": [{ nlc: 697, modes: [0] }],
  "stamford brook": [{ nlc: 713, modes: [0] }],
  "stamford hill": [{ nlc: 6968, modes: [20] }],
  "stanmore": [{ nlc: 714, modes: [0] }],
  "star lane": [{ nlc: 889, modes: [5] }],
  "stepney green": [{ nlc: 715, modes: [0] }],
  "stockwell": [{ nlc: 716, modes: [0] }],
  "stoke newington": [{ nlc: 6934, modes: [20] }],
  "stonebridge park": [{ nlc: 717, modes: [0, 20] }],
  "stratford": [{ nlc: 719, modes: [0, 5, 20, 101] }],
  "stratford high street": [{ nlc: 749, modes: [5] }],
  "stratford international": [{ nlc: 504, modes: [5] }],
  "sudbury hill": [{ nlc: 720, modes: [0] }],
  "sudbury town": [{ nlc: 721, modes: [0] }],
  "surrey quays": [{ nlc: 1083, modes: [20] }],
  "swiss cottage": [{ nlc: 723, modes: [0] }],
  "sydenham": [{ nlc: 5437, modes: [20] }],
  "taplow": [{ nlc: 3151, modes: [101] }],
  "temple": [{ nlc: 724, modes: [0] }],
  "theobalds grove": [{ nlc: 6949, modes: [20] }],
  "theydon bois": [{ nlc: 725, modes: [0] }],
  "tooting bec": [{ nlc: 726, modes: [0] }],
  "tooting broadway": [{ nlc: 727, modes: [0] }],
  "tottenham court road": [{ nlc: 728, modes: [0, 101] }],
  "tottenham hale": [{ nlc: 729, modes: [0] }],
  "totteridge and whetstone": [{ nlc: 730, modes: [0] }],
  "tower gateway": [{ nlc: 864, modes: [5] }],
  "tower hill": [{ nlc: 731, modes: [0] }],
  "tufnell park": [{ nlc: 733, modes: [0] }],
  "turkey street": [{ nlc: 6952, modes: [20] }],
  "turnham green": [{ nlc: 734, modes: [0] }],
  "turnpike lane": [{ nlc: 735, modes: [0] }],
  "twyford": [{ nlc: 3155, modes: [101] }],
  "upminster": [{ nlc: 736, modes: [0, 20] }],
  "upminster bridge": [{ nlc: 737, modes: [0] }],
  "upney": [{ nlc: 738, modes: [0] }],
  "upper holloway": [{ nlc: 1524, modes: [20] }],
  "upton park": [{ nlc: 739, modes: [0] }],
  "uxbridge": [{ nlc: 740, modes: [0] }],
  "vauxhall": [{ nlc: 777, modes: [0] }],
  "victoria": [{ nlc: 741, modes: [0] }],
  "walthamstow central": [{ nlc: 742, modes: [0, 20] }],
  "walthamstow queens road": [{ nlc: 7407, modes: [20] }],
  "wandsworth road": [{ nlc: 5372, modes: [20] }],
  "wanstead": [{ nlc: 743, modes: [0] }],
  "wanstead park": [{ nlc: 7408, modes: [20] }],
  "wapping": [{ nlc: 1085, modes: [20] }],
  "warren street": [{ nlc: 745, modes: [0] }],
  "warwick avenue": [{ nlc: 746, modes: [0] }],
  "waterloo": [{ nlc: 747, modes: [0] }],
  "watford": [{ nlc: 748, modes: [0] }],
  "watford high street": [{ nlc: 1455, modes: [20] }],
  "watford junction": [{ nlc: 1402, modes: [20] }],
  "wembley central": [{ nlc: 751, modes: [0, 20] }],
  "wembley park": [{ nlc: 752, modes: [0] }],
  "west acton": [{ nlc: 753, modes: [0] }],
  "west brompton": [{ nlc: 755, modes: [0, 20] }],
  "west croydon": [{ nlc: 5411, modes: [20] }],
  "west drayton": [{ nlc: 3174, modes: [101] }],
  "west ealing": [{ nlc: 3188, modes: [101] }],
  "west finchley": [{ nlc: 756, modes: [0] }],
  "west ham": [{ nlc: 757, modes: [0, 5] }],
  "west hampstead": [{ nlc: 1421, modes: [20] }, { nlc: 758, modes: [0] }],
  "west harrow": [{ nlc: 759, modes: [0] }],
  "west india quay": [{ nlc: 866, modes: [5] }],
  "west kensington": [{ nlc: 760, modes: [0] }],
  "west ruislip": [{ nlc: 762, modes: [0] }],
  "west silvertown": [{ nlc: 559, modes: [5] }],
  "westbourne park": [{ nlc: 754, modes: [0] }],
  "westferry": [{ nlc: 865, modes: [5] }],
  "westminster": [{ nlc: 761, modes: [0] }],
  "white city": [{ nlc: 764, modes: [0] }],
  "white hart lane": [{ nlc: 6956, modes: [20] }],
  "whitechapel": [{ nlc: 763, modes: [0, 20, 101] }],
  "willesden green": [{ nlc: 765, modes: [0] }],
  "willesden junction": [{ nlc: 766, modes: [0, 20] }],
  "wimbledon": [{ nlc: 767, modes: [0] }],
  "wimbledon park": [{ nlc: 768, modes: [0] }],
  "wood green": [{ nlc: 770, modes: [0] }],
  "wood lane": [{ nlc: 599, modes: [0] }],
  "wood street": [{ nlc: 6954, modes: [20] }],
  "woodford": [{ nlc: 769, modes: [0] }],
  "woodgrange park": [{ nlc: 7467, modes: [20] }],
  "woodside park": [{ nlc: 771, modes: [0] }],
  "woolwich": [{ nlc: 6562, modes: [101] }],
  "woolwich arsenal": [{ nlc: 573, modes: [5] }],
};

/** Resolve a station name (+ claim ModeId) to its NLC via the bundled map. */
export function lookupNlc(name: string, modeId: number | null = null): number | null {
  return resolveNlc(name, modeId, STATION_NLC);
}
